### ISSUE TITLE
Plugin DirEve: Incluir novo cluster Área Temática

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin-idx#2]
Nome do cluster: thematic_area

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/direve-wp-plugin/issues/31

**Comment by viniciusandrade** [comment]
@wilsonmoura cluster **thematic_area_display** disponível no índice para eventos. 
Estou realizando a re-indexação da base para popular o índice, isso deve demorar algumas horas mas já é possível realizar os testes e ajustes no plugin.

**Comment by wilsonmoura** [comment]
@viniciusandrade validado!
