### ISSUE TITLE
Plugin DirEve: Incluir novo cluster Ano

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin-idx#3]
Nome do cluster: year (campo start_date)

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/direve-wp-plugin/issues/36

**Comment by viniciusandrade** [comment]
@wilsonmoura cluster **publication_year** disponível no índice para eventos. 
Estou realizando a re-indexação da base para popular o índice, isso deve demorar algumas horas mas já é possível realizar os testes e ajustes no plugin.

**Comment by wilsonmoura** [comment]
@viniciusandrade validado!
