### ISSUE TITLE
Plugin LeisRef: Incluir novo cluster "Indexado em"

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin-idx#4]
Nome do cluster: indexed_database

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/leisref-wp-plugin/issues/58

**Comment by viniciusandrade** [comment]
@wilsonmoura verifiquei que o cluster **indexed_database** já esta disponível e populado com os dados dos registros de legislação ... acredito que seja somente ajuste no plugin para mostrar o filtro.

**Comment by viniciusandrade** [comment]
![image](https://github.com/bireme/fi-admin-idx/assets/349287/4d624f32-2949-4bc3-b7cd-e395aafd47db)

Printscreen do Solr Admin para este filtro.
