### ISSUE TITLE
Plugin LIS: Incluir novo cluster Área Temática

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin-idx#5]
Nome do cluster: thematic_area

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/lis-wp-plugin/issues/19

**Comment by viniciusandrade** [comment]
@wilsonmoura favor verificar se o filtro **thematic_area_display** atende a necessidade.

**Comment by wilsonmoura** [comment]
@viniciusandrade validado!
