### ISSUE TITLE
Plugin FI-Multimedia: Incluir novo cluster Área Temática #5

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/fi-admin-idx#7]
Nome do cluster: thematic_area

**Comment by wilsonmoura** [comment]
Relacionado com https://github.com/bireme/fi-multimedia-wp-plugin/issues/24

**Comment by viniciusandrade** [comment]
@wilsonmoura favor verificar se o filtro **thematic_area_display** serviria para este caso.

**Comment by wilsonmoura** [comment]
@viniciusandrade validado!
